### ISSUE TITLE
Preview changes (desktop/mobile difference)

### ISSUE THREAD

**Issue by gpsietzema** [Sterc/SEOPro#41]
There have been some changes in Google which has consequences for the Preview features in SEO Tab. Google SERP's show different in Mobile and Desktop search results

**Comment by sdrenth** [comment]
I've done some research into this subject and google has changed their SERP length calculation. Google doesn't count characters anymore but shows an ellipsis based on the pixel length of the title/description. This also means that the width of a character and for example its font-weight are now as well of importance to the amount of characters that are shown in the SERP.

Because it is now based on pixel length instead of the amount of characters the length may vary across devices because of the font rendering. 

The limits in pixels are as follows:
Title: Max 469px;
Description: Around 920px;

I recommend calculating the width of the title/description on the text with the Google CSS applied and limit the title/description based on pixels instead of characters.

**Comment by christianseel** [comment]
Thats part of what happened already here with `text-overflow: ellipsis`:
https://github.com/Sterc/SEOPro/issues/32
