### ISSUE TITLE
Feature request: adjusting meta lengths to 2018 guide lines

### ISSUE THREAD

**Issue by jopberkhout** [Sterc/SEOPro#74]
Since 2018 Google changed the way they look at and display the length of meta data. The general assumption is that Google Search now displays up to 76 characters of the page title (70 is safe) and up to 325 in the description (300 is safe). You can adjust the amount of characters in SEO Pro, but the description field still displays a warning and the preview pane still truncates. It would be nice if it would support the new guide lines without having to hack anything.

![seo-pro](https://user-images.githubusercontent.com/2864141/35519895-d2ebd56c-0515-11e8-97ea-9eda57be3e35.png)

**Comment by joeke** [comment]
@jopberkhout Hi Jop! Yeah this is due to the max length (191 chars in modx 2.6.1) on the description field in the modx_site_content table. So this is either something to be fixed in core modx (convert the description to TEXT), or SeoPro should use some custom field for the description. We'll figure something out, and get back to you asap

**Comment by jopberkhout** [comment]
@joeke You are right, I figured that out after posting it. Your solution sounds good: converting it to TEXT. The Google Preview pane is pretty easy to fix though I presume.

**Comment by joeke** [comment]
@jopberkhout This will be fixed with the upcoming 1.3.0 version.

**Comment by joeke** [comment]
@jopberkhout And here it is: https://modx.com/extras/package/seopro
